namespace Haasonline.Public.LocalApi.CSharp.Enums
{
    public enum EnumIndicator
    {
        /* A */
        Aroon = 0,
        AroonOscillator = 1,
        AwesomeOscillator = 2,
        /* B */
        Blind = 3,
        BOP = 4,
        BBands = 5,
        BBandsB = 6,
        BBandsW = 7,
        BuyLowSellHighFixed = 8,
        BuyLowSellHighDynamic = 9,
        BBandsPshai = 51,
        /* C */
        CCI = 11,
        CMO = 12,
        CoppockCurve = 13,
        CRSI = 14,
        CandlePattern = 15,
        /* D */
        DEMA = 16,
        DEMA_New = 52,
        DonchianChannels = 17,
        DPO = 18,
        /* E */
        EMA = 19,
        EMA_New = 53,
        Elliot = 20,
        /* F */
        FastRSI = 21,
        Fibonacci = 22,
        Fractial = 23,
        /* G */
        /* H */
        /* I */
        IchimokuClouds = 24,
        /* J */
        JohnsCandelier = 25,
        /* K */
        KeltnerChannels = 26,
        KAMA = 27,
        KAMA_New = 54,
        KeltnerChannels_New = 55,
        /* L */
        /* M */
        MACD = 28,
        MACD_New = 69,
        MFI = 29,
        Momentum = 70,
        /* N */
        /* O */
        /* P */
        /* Q */
        /* R */
        ROC = 30,
        ROCAlt = 31,
        RSI = 32,
        RSI_New = 59,
        RegressionSlobe = 33,
        /* S */
        SAR = 34,
        SlowRSI = 35,
        SMA = 36,
        StochRSI = 37,
        StochRSI_New = 62,
        Stochastic = 38,
        Stochastic2 = 39,
        SmallFractial = 40,
        ScriptIndicator = 41,
        /* T */
        TEMA = 42,
        TEMA_New = 63,
        TRIX = 43,
        TRIX_New = 64,
        TRIMA = 44,
        TRIMA_New = 65,
        TD = 71,
        //        TelegramIndicator = 45,
        TimedBlind = 49,
        /* U */
        UltimateOscillator = 46,
        UltimateOscillator_New = 66,
        /* V */
        /* W */
        WMA = 47,
        WilliamsW = 48,
        WilliamsR_New = 67,
        /* X */
        /* Y */
        /* Z */
        HaasScriptIndicator = 50
    }
}